# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MAKEFILE                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ghoyuelo <ghoyuelo@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/11/30 13:46:25 by ghoyuelo          #+#    #+#              #
#    Updated: 2023/11/30 13:46:25 by ghoyuelo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #




NAME = minishell

//INC	= ./minishell.h

CC = gcc -Wall -Werror -Wextra

RM = rm -f

SRCS = builtin/tester_main.c \
           builtin/ft_echo.c \
           builtin/ft_pwd.c \
           builtin/ft_env.c \
           builtin/ft_unset.c \
           builtin/ft_export.c \
           builtin/ft_exit.c \
           builtin/utils_1.c \
           builtin/utils_2.c \
           #builtin/ft_cd.c 

OBJS = $(SRCS:.c=.o)

all: $(NAME)

%.o: %.c
        $(CC) -c $< -o $@

$(NAME): $(OBJS)
        $(CC) $(OBJS) -o $(NAME)

clean:
        $(RM) $(OBJS)